/*
 FusionCharts JavaScript Library
 Copyright FusionCharts Technologies LLP
 License Information at <http://www.fusioncharts.com/license>

 @author FusionCharts Technologies LLP
 @version fusioncharts/3.2.4-sr1.10100
*/
FusionCharts(["private","modules.renderer.highcharts-gradientlegend",function(){function aa(a,e,b){var j=a[0],f=a[1],a=a[2];j+=(e[0]-j)*b;f+=(e[1]-f)*b;e=a+(e[2]-a)*b;return{hex:(z+(j<<16|f<<8|e).toString(16)).slice(-6),rgb:[j,f,e]}}function n(a,e){return a.maxvalue-e.maxvalue}function $(a){var l=a.colorRange||{},j=a.dataMin,b=a.dataMax,f=a.sortLegend||!1,h=a.mapByCategory||!1,d=a.defaultColor,r=a.numberFormatter,c=l.color,a=this.colorArr=[],D,m,u,k,q;this.mapByCategory=h;if(l.mapbypercent==="1")this.mapbypercent=
!0;if(l.gradient==="1"&&!h){this.gradient=!0;D=e(S(l.startcolor,l.mincolor,l.code));f=qa(e(S(D,d,"CCCCCC")));h=this.scaleMin=I(l.startvalue,l.minvalue,this.mapbypercent?0:j);a.push({code:D,maxvalue:h,label:X(l.startlabel),codeRGB:qa(D)});if(c&&(m=c.length))for(j=0;j<m;j+=1)d=c[j],D=e(S(d.color,d.code)),k=I(d.value,d.maxvalue),q=I(d.minvalue),k>h&&a.push({code:D,maxvalue:k,userminvalue:q,label:X(S(d.label,d.displayvalue)),codeRGB:qa(D)});a.sort(n);m=a.length;for(j=1;j<m;j+=1)d=a[j],D=d.maxvalue-h,
D>0?(d.minvalue=h,d.range=D,h=d.maxvalue):(a.splice(j,1),j-=1,m-=1);if(a.length>=2)this.scaleMax=h,a[j-1].label=S(l.endlabel,a[j-1].label,a[j-1].displayvalue);if(a.length===1)k=I(l.maxvalue,this.mapbypercent?100:b),a.push({minvalue:h,maxvalue:k,range:k-h,label:l.endlabel}),this.scaleMax=k,delete a[0].code;l=a[0];b=a[a.length-1];if(!l.code||!b.code){m=Y(f);m={minRGB:va((m[2]=0,m)),maxRGB:va((m[2]=100,m))};if(!l.code)l.codeRGB=m.minRGB,l.code=wa(m.minRGB);if(!b.code)b.codeRGB=m.maxRGB,b.code=wa(m.maxRGB)}m=
a.length;for(j=1;j<m;j+=1)if(d=a[j],d.code){if(u){b=d;q=l.maxvalue;for(c=b.maxvalue-q;u<j;u+=1)f=a[u],D=aa(l.codeRGB,b.codeRGB,(f.maxvalue-q)/c),f.code=D.hex,f.codeRGB=D.rgb}u=null;l=d}else u=u||j;if(this.scaleMin===void 0||this.scaleMax===void 0)this.noValidRange=!0}else if(c&&(m=c.length)){for(j=0;j<m;j+=1)d=c[j],D=S(d.color,d.code),k=I(d.maxvalue),q=I(d.minvalue),u=S(d.label,d.displayvalue,h?V:r.dataLabels(q)+" - "+r.dataLabels(k)),(D&&k>q||h&&u)&&a.push({code:D,maxvalue:k,minvalue:q,label:X(u),
labelId:u.toLowerCase()});a.length?f&&a.sort(n):this.noValidRange=!0}}function fa(e,j){return j?i(e*100)/100+a:ra(e,V).toString()}var b=this.hcLib,I=b.pluckNumber,z=b.COLOR_BLACK,g=b.COLOR_GLASS,sa=b.FC_CONFIG_STRING,ba=b.graphics,va=ba.HSBtoRGB,Y=ba.RGBtoHSB,wa=ba.RGBtoHex,qa=ba.HEXtoRGB,ca=b.COMMASTRING,V=b.BLANKSTRING,X=b.parseUnsafeString,p=b.graphics.convertColor,s=b.POSITION_RIGHT,la=b.POSITION_LEFT,Z=b.POSITION_CENTER,xa=b.graphics.getDarkColor,ta=b.graphics.getLightColor,S=b.pluck,ra=b.getValidValue,
M=b.Highcharts,ba=M.legendTypes,za=M.hasTouch,na=M.getTouchEvent,ya=M.getPosition,T=M.addEvent,i=Math.round,G=Math.max,Q=Math.min,o=Math.abs,a="%",j={pageX:0,pageY:0},e=function(a){return a&&a.replace(/^#?([a-f0-9]+)/ig,"$1")};$.prototype={getColorObj:function(a){var e=this.colorArr,j=this.gradient?1:0,b=e[j];if(this.mapByCategory){for(a=X(a).toLowerCase();b;){if(b.labelId===a)return{code:b.code,seriesIndex:j};j+=1;b=e[j]}return{outOfRange:!0}}else if(this.gradient)if(this.scaleMin<=a&&this.scaleMax>=
a){for(;b&&b.maxvalue<a;)j+=1,b=e[j];a=(a-b.minvalue)/b.range;return{code:aa(e[j-1].codeRGB,b.codeRGB,a).hex}}else return{outOfRange:!0};else{for(;b;){if(b.maxvalue>=a&&b.minvalue<=a)return{code:b.code,seriesIndex:j};j+=1;b=e[j]}return{outOfRange:!0}}}};$.prototype.constructor=$;b.colorRange=$;var U=b.configureGradientLegendOptions=function(a,e){var j=a.legend,b=e.chart;j.legendSliderBorderWidth=I(b.legendpointerborderthickness,1);j.legendSliderBorderColor=p(S(b.legendpointerbordercolor,z),I(b.legendpointerborderalpha,
100));j.legendSliderWidth=I(b.legendpointerwidth,b.legendpointerswidth,12);j.legendSliderHeight=I(b.legendpointerheight,b.legendpointersheight,12);j.legendColorBoxBorderColor=j.borderColor;j.legendColorBoxBorderWidth=j.borderWidth;j.legendScaleColor=p(S(b.legendscalelinecolor,z),I(b.legendscalelinealpha,100));j.legendScalePadding=I(b.legendscalepadding,4);j.legendScaleLineThickness=I(b.legendscalelinethickness,1);j.legendScaleTickDistance=I(b.legendscaletickdistance,6);j.itemStyle.cursor="default";
j.interActivity=I(b.interactivelegend,1)};b.placeGLegendBlockRight=function(a,j,e,g,f){b.configureLegendOptions(a,j.chart,!0,f,e);U(a,j);var f=a[sa].smartLabel,h=a.legend,d,r,c=h.textPadding=2,D=c*2,m=h.title.padding,u=0,k=0,q=2*h.padding,j=I(j.chart.legendpadding,7)+h.borderWidth/2+1,F=a.colorRange||{},t=F.colorArr,da=F.mapbypercent,oa=F.scaleMin,Ga=F.scaleMax-oa,x=h.legendSliderWidth,A=h.legendSliderHeight/2,K=h.legendScalePadding,y=h.legendScaleTickDistance;r=h.itemStyle||{};var w=I(parseInt(r.lineHeight,
10)||12),p=w*0.75,i=e-q,C,H,n=0,s,o,E,R,z,S;g-=q;if(!F.noValidRange&&t&&(H=t.length)>1){H-=1;if(h.title.text!==V)f.setStyle(h.title.style),k=f.getSmartText(h.title.text,i,G(w,g/4)),h.title.text=k.text,u=k.width+q,g-=k=k.height+m;i-=y+K+x;h.colorBoxX=x;m=G(w,i/2);i=Q(i-m-4,w);s=G(w,g/2);C=g/4;f.setStyle(r);w=t[0];w.scaleLabel=fa(w.maxvalue,da);d=f.getSmartText(w.label,C,i);w.label=d.text;K=d.height;w.labelY=p-d.height/2;r=f.getSmartText(w.scaleLabel,m,s);w.scaleLabel=r.text;y=r.height/2;F=r.width;
w.scaleLabelY=p-r.height/2;h.colorBoxY=G(y,d.width+D,A)+k;w=S=t[H];w.scaleLabel=fa(w.maxvalue,da);d=f.getSmartText(w.label,C,i);w.label=d.text;K=G(K,d.height);w.labelY=p-d.height/2;r=f.getSmartText(w.scaleLabel,m,s);w.scaleLabel=r.text;F=G(F,r.width);C=r.height/2;A=G(d.width+D,C,A);w.scaleLabelY=p-r.height/2;h.colorBoxHeight=A=g-h.colorBoxY-A;s=A-C;o=A/Ga;R=Q(A-n,s-y)-4;for(C=1;C<H;C+=1)w=t[C],E=(w.maxvalue-oa)*o,d=f.getSmartText(w.label,Q(E-n,A-E)*2,i),w.label=d.text,K=G(K,d.height),w.labelY=p-d.height/
2,d=d.width/2,w.scaleLabel=fa(w.maxvalue,da),r=f.getSmartText(w.scaleLabel,m,Q(E-y,s-E)*2),w.scaleLabel=r.text,F=G(F,r.width),z=r.height/2,w.scaleLabelY=p-r.height/2,R=Q(R,(E-G(z+y,d+n)-4)*Ga/w.range),n=d+E,y=z+E;R=G(Q(R,(Q(s-y,A-n)-4)*Ga/S.range,g*0.3),0);h.colorBoxHeight-=R;h.colorBoxWidth=K&&K+D||15;h.height=h.totalHeight=g+k+q-R;h.width=(F&&F+c)+h.colorBoxWidth+x+h.legendScaleTickDistance+h.legendScalePadding+q;if(h.width<u)h.colorBoxX+=(u-h.width)/2,h.width=u;if(h.width>e)h.width=e;j+=h.width;
a.chart.marginRight+=j;return j}else return h.enabled=!1,0};b.placeGLegendBlockBottom=function(a,j,e,g,f){b.configureLegendOptions(a,j.chart,!1,f,e);U(a,j);var f=a[sa].smartLabel,h=a.legend,d,r,c=h.textPadding=2,D=h.title.padding,m=0,u=0,k=2*h.padding,j=I(j.chart.legendpadding,7)+h.borderWidth/2+1,q=a.colorRange||{},F=q.colorArr,t=q.mapbypercent,da=q.scaleMin,oa=q.scaleMax-da,p=h.legendSliderWidth,x=h.legendSliderHeight,A=h.legendScalePadding,K=h.legendScaleTickDistance,y=h.itemStyle||{},w=I(parseInt(y.lineHeight,
10)||12),i=w*0.75,s=g-k,C,n,o,z=0,T,E,R;e-=k;if(!q.noValidRange&&F&&(n=F.length)>1){n-=1;if(h.title.text!==V)f.setStyle(h.title.style),u=f.getSmartText(h.title.text,e,s/3),h.title.text=u.text,m=u.width+k,s-=u=u.height+D;s-=K+A+x;D=G(w,s/2);w=Q(s-D-4,w);f.setStyle(y);C=e/4;o=C*2;q=F[0];q.scaleLabel=fa(q.maxvalue,t);d=f.getSmartText(q.label,C,w);q.label=d.text;y=d.height;q.labelY=i-d.height/2;r=f.getSmartText(q.scaleLabel,o,D);q.scaleLabel=r.text;s=r.width/2;A=r.height;if(!q.code)q.code=S(h.minColor,
"CCCCCC");h.colorBoxX=G(s,d.width+c,p);q=K=F[n];q.scaleLabel=fa(q.maxvalue,t);d=f.getSmartText(q.label,C,w);q.label=d.text;y=G(y,d.height);q.labelY=i-d.height/2;r=f.getSmartText(q.scaleLabel,o,D);q.scaleLabel=r.text;A=G(A,r.height);q=r.width/2;p=G(d.width+c,q,p);h.colorBoxWidth=p=e-h.colorBoxX-p;o=p-q;T=p/oa;R=Q(p-z,o-s)-4;for(C=1;C<n;C+=1)q=F[C],E=(q.maxvalue-da)*T,d=f.getSmartText(q.label,Q(E-z,p-E)*2,w),q.label=d.text,y=G(y,d.height),q.labelY=i-d.height/2,d=d.width/2,q.scaleLabel=fa(q.maxvalue,
t),r=f.getSmartText(q.scaleLabel,Q(E-s,o-E)*2,D),q.scaleLabel=r.text,A=G(A,r.height),r=r.width/2,R=Q(R,(E-G(r+s,d+z)-4)*oa/q.range),z=d+E,s=r+E;R=G(Q(R,(Q(o-s,p-z)-4)*oa/K.range,e*0.3),0);h.colorBoxWidth-=R;h.width=e+k-R;if(h.width<m)h.colorBoxX+=(m-h.width)/2,h.width=m;h.colorBoxY=u+x;h.colorBoxHeight=y&&y+2*c||15;h.height=h.totalHeight=(A&&A+c)+h.colorBoxHeight+u+x+h.legendScaleTickDistance+h.legendScalePadding+k;if(h.height>g)h.height=g;j+=h.height;a.chart.marginBottom+=j;return j}else return h.enabled=
!1,0};var oa=function(){return{point:this}},M=M.extendClass(ba.point,{colorizeItem:function(){},destroy:function(){var a=this.elements,j=a.box,e=a.legendGroup,b=a.legendScroller,f=a.legendClip,h=a.colorBox,d=a.colorBoxEffect,r=a.slider1,c=a.slider1Effect,D=a.slider2,m=a.slider2Effect;if(h)a.colorBox=h.destroy();if(d)a.colorBoxEffect=d.destroy();if(r)a.slider1=r.destroy();if(c)a.slider1Effect=c.destroy();if(D)a.slider2=D.destroy();if(m)a.slider2Effect=m.destroy();if(j)a.box=j.destroy();if(e)a.legendGroup=
e.destroy();if(b)a.legendScroller=b.destroy();if(f)a.legendClip=f.destroy()},renderAllItems:function(){var a=this.chart,e=a.plotLeft,b=a.plotTop,U=a.plotWidth,f=a.plotHeight,h=a.tooltip,d=a.options.colorRange,r,c,D,m,u=this.conf,k=u.fontSize,q=u.padding,F=this.renderer,t=this.options,da=t.itemStyle,pa=t.symbolStyle,n=t.interActivity,x=this.elements,A=x.legendGroup,K=u.horizontal,y,w,ja,G,C,H,u=0,I=t.lighting3d,aa,X,E=t.colorBoxX,R=t.colorBoxY,ia=aa=t.colorBoxWidth,M=X=t.colorBoxHeight,$=this.allItems,
fa={FCcolor:{color:V,alpha:V,angle:0,ratio:V}},ma=fa.FCcolor;E+=q;var q=R+q,N,R=t.legendColorBoxBorderColor,ba=t.legendColorBoxBorderWidth,Aa=["M"],La=t.legendScaleColor;C=t.legendScalePadding;var Y=t.legendScaleLineThickness,ua=Y%2/2;c=t.legendScaleTickDistance;N=t.legendSliderWidth;y=t.legendSliderHeight;m=M/2;H=ia/2;var B=N/2,L=y/2,ka,ea,ga,O,W;ja=0;Q(N,y);var Ba=ta("ABABAB",50),Ca=xa("ABABAB",70),t=p("ABABAB",100),Ca=p(Ca,100),Ba=p(Ba,100),Ha,P={isFirst:!0},J={},Da,Ea,Ia=a.series,Ja;if(d&&(r=
d.colorArr)&&(D=r.length)>1){P.toolText=Da=w=d.scaleMin;J.toolText=Ea=ja=d.scaleMax;G=ja-w;P.snapPX=J.snapPX=0;P.tooltipConstraint=J.tooltipConstraint="chart";P.getLabelConfig=J.getLabelConfig=oa;P.series=J.series={};P.tooltipPos=[0,0];J.tooltipPos=[0,0];J.tooltipOffsetReference=P.tooltipOffsetReference=ya(a.container);J.tooltipOffsetReference.left=P.tooltipOffsetReference.left+=e-20;J.tooltipOffsetReference.top=P.tooltipOffsetReference.top+=b;if(K){P.tooltipPos[1]=J.tooltipPos[1]=f+b;U=i(E-B)+0.5;
f=i(E+B)+0.5;d=i(q-y)+0.5;y=i(q+M)+0.5;ka=i(E-2)+0.5;N=i(E+2)+0.5;ea=i(E)+0.5;ga=i(q)+0.5;O=q-L/2;W=i(O-L)+0.5;O=i(O)+0.5;ja=E-B/2;H=i(ja+B)+0.5;ja=i(ja)+0.5;X/=2;B=["M",U,d,"L",f,d,f,ga,N,ga,ea,y,ka,ga,U,ga,"Z","M",ja,W,"L",ja,O,"M",ea,W,"L",ea,O,"M",H,W,"L",H,O];L=["M",U,d+1,"L",f,d+1,"M",ja-1,W,"L",ja-1,O,"M",ea-1,W,"L",ea-1,O,"M",H-1,W,"L",H-1,O];C=q+M+C;ja=i(C+c)+ua;C=i(C)+ua;d=ja+k;N=q+m;f=D-1;for(c=0;c<D;c+=1)m=r[c],H=(m.maxvalue-w)/G,y=ia*H+E,k=i(y)+ua,c?(ma.ratio+=ca,ma.color+=ca,ma.alpha+=
ca,Aa.push("L",k,C,k,ja,"M",k,C),c===f?(U=la,k=y+2):(U=Z,k=y)):(Aa.push(k,C,"L",k,ja,"M",k,C),U=s,k=y-2),ma.ratio+=(H-u)*100,ma.color+=S(m.code,z),ma.alpha+=S(m.alpha,100),u=H,m.legendItem=F.text(m.label,k,N+m.labelY).css(da).attr({zIndex:3,align:U}).add(A),m.legendSymbol=F.text(m.scaleLabel,y,d).css(da).attr({zIndex:2,align:Z}).add(A),$.push(m);P.xMin=J.xMin=0;P.xMax=J.xMax=ia;P.yMin=J.yMin=0;P.yMax=J.yMax=0;P.y=J.y=0;P.x=0;J.x=ia}else{P.tooltipPos[0]=J.tooltipPos[0]=U+e;ja=270;ma.angle=90;U=E-N;
f=E+ia;d=q-L;y=q+L;U=i(E-N)+0.5;f=i(E)+0.5;d=i(q-L)+0.5;y=i(q+L)+0.5;ka=i(E+ia)+0.5;ga=i(q-2)+0.5;O=i(q+2)+0.5;W=i(q)+0.5;N=E-B/2;ea=i(N-L)+0.5;N=i(N)+0.5;k=q-L/2;m=i(k+L)+0.5;k=i(k)+0.5;aa/=2;B=["M",U,d,"L",f,d,f,ga,ka,W,f,O,f,y,U,y,"Z","M",ea,k,"L",N,k,"M",ea,W,"L",N,W,"M",ea,m,"L",N,m];L=["M",U+1,d,"L",U+1,y,"M",ea,k-1,"L",N,k-1,"M",ea,W-1,"L",N,W-1,"M",ea,m-1,"L",N,m-1];k=E+ia+C;d=i(k+c)+ua;k=i(k)+ua;N=E+H;f=D-1;for(c=0;c<D;c+=1)m=r[c],H=(m.maxvalue-w)/G,y=M*H+q,C=i(y)+ua,c?(ma.ratio+=ca,ma.color+=
ca,ma.alpha+=ca,Aa.push("L",k,C,d,C,"M",k,C),c===f?(U=s,C=y+2):(U=Z,C=y)):(Aa.push(k,C,"L",d,C,"M",k,C),U=la,C=y-2),ma.ratio+=(H-u)*100,ma.color+=S(m.code,z),ma.alpha+=S(m.alpha,100),u=H,m.legendItem=F.text(m.label,N+m.labelY,C).css(da).attr({zIndex:3,align:U,rotation:ja}).add(A),m.legendSymbol=F.text(m.scaleLabel,d,y+m.scaleLabelY).css(da).attr({zIndex:2,align:la}).add(A),$.push(m);P.xMin=J.xMin=0;P.xMax=J.xMax=0;P.yMin=J.yMin=0;P.yMax=J.yMax=M;P.x=J.x=0;P.y=0;J.y=M}x.colorBox=F.rect(E,q,ia,M,0,
1).attr({zIndex:2,fill:fa,stroke:R,strokeWidth:ba}).add(A);if(I)x.colorBoxEffect=F.rect(E,q,aa,X,0,1).attr({zIndex:2,fill:g,strokeWidth:0}).add(A);x.scale=F.path(Aa).attr({zIndex:2,stroke:La,strokeWidth:Y}).add(A);Ha=function(a,c,f){var d,h=0,j=Ia&&Ia.length,k;K?(d=a*G/ia+w,a=a||0.01):(d=c*G/M+w,c=c||0.01);f?(x.slider1.translate(a,c).toFront(),x.slider1Effect.translate(a,c).toFront(),Da=d,P.toolText=i(Da*100)/100):(x.slider2.translate(a,c).toFront(),x.slider2Effect.translate(a,c).toFront(),Ea=d,J.toolText=
i(Ea*100)/100);n&&(Ja=clearTimeout(Ja),Ja=setTimeout(function(){for(;h<j;h+=1)k=Ia[h],k.setScaleRange&&k.setScaleRange(Da,Ea)},100))};r=function(c){var f=c.data,d=za&&na(c)||j,k,m=k=0,q,r=f.isFirst,u=r?J:P;if(c.type==="dragstart")f.tooltipOffsetReference=ya(a.container),f.tooltipOffsetReference.left+=e-20,f.tooltipOffsetReference.top+=b,f.lastDraggedX=f.dragStartX=c.pageX||d.pageX,f.lastDraggedY=f.dragStartY=c.pageY||d.pageY;else{if(K){k=f.x+((c.pageX||d.pageX)-f.dragStartX);k<=0&&(k=0);k>ia&&(k=
ia);if(r?k>u.x:k<u.x)k=u.x;if(o(k-f.lastDraggedX)>=(f.snapPX||0))q=!0}else{m=f.y+((c.pageY||d.pageY)-f.dragStartY);m<=0&&(m=0);m>M&&(m=M);if(r?m>u.y:m<u.y)m=u.y;if(o(m-f.lastDraggedY)>=(f.snapPX||0))q=!0}if(c.type==="drag"){if(q)f.lastDraggedX=k,f.lastDraggedY=m,Ha(k,m,r),Fa(c,!0)}else delete f.lastDraggedX,delete f.lastDraggedY,delete f.dragStartX,delete f.dragStartY,f.x=k,f.y=m,Ha(k,m,r),h&&h.hide()}};x.slider1=F.path(B).attr({zIndex:3,fill:t,strokeWidth:1,stroke:Ca}).css(pa).add(A);x.slider1Effect=
F.path(L).attr({zIndex:3,fill:"none",strokeWidth:1,stroke:Ba}).css(pa).add(A);x.slider2=F.path(B).attr({zIndex:3,fill:t,strokeWidth:1,stroke:Ca}).css(pa).add(A).translate(J.x,J.y);x.slider2Effect=F.path(L).attr({zIndex:3,fill:"none",strokeWidth:1,stroke:Ba}).css(pa).translate(J.x,J.y).add(A);T(x.slider1.element,"dragstart dragend drag",r,P);T(x.slider1Effect.element,"dragstart dragend drag",r,P);T(x.slider2.element,"dragstart dragend drag",r,J);T(x.slider2Effect.element,"dragstart dragend drag",r,
J);var Fa=function(a,c){var f=a.data,d=f.tooltipOffsetReference;if((c||f.lastDraggedX===void 0)&&h)K?f.tooltipPos[0]=(a.pageX||a.x||a.offsetX)-d.left:f.tooltipPos[1]=(a.pageY||a.y||a.offsetY)-d.top,h.refresh(f)},F=function(a){a.data.lastDraggedX===void 0&&h&&h.hide()};T(x.slider1.element,"mouseout",F,P);T(x.slider1Effect.element,"mouseover",Fa,P);T(x.slider1Effect.element,"mouseout",F,P);T(x.slider2.element,"mouseover",Fa,J);T(x.slider2.element,"mouseout",F,J);T(x.slider2Effect.element,"mouseover",
Fa,J);T(x.slider2Effect.element,"mouseout",F,J)}}});ba.gradient=M}]);
FusionCharts(["private","modules.renderer.highcharts-annotations",function(){var aa=this.core,n=this.hcLib,$=n.Highcharts,fa=$.each,b=$.addEvent,I=$.removeEvent,z=$.hasTouch,g=$.hasSVG,sa=z?6:5,ba="rgba(192,192,192,"+(g?1.0E-6:0.0020)+")",va=Math.min,Y=Math.max,wa=Math.sin,qa=Math.cos,ca=Math.PI,V=ca/180,X=this.extend,p=n.pluck,s=n.pluckNumber,la=n.graphics.convertColor,Z=n.getDashStyle,xa=n.getValidValue,ta=n.parseUnsafeString,S=n.setImageDisplayMode,ra=n.graphics.parseColor,M=n.setLineHeight,za=
{style:{}},na=function(){return this},ya=function(a,j){var e;if(j>360||j<-360)j%=360;if(a>360||a<-360)a%=360;e=a-j;if(e>360||e<-360)e%=360,j=a-e;j=360-j;a=360-a;if(a>360||j>360)a-=360,j-=360;return{start:a,end:j,angle:-e}},T=function(a,j,e,b){var g=0,v=0,j=j===void 0||j===null?1:j,l;if(!a||!a.toString)return e;a=a.toLowerCase().replace(/\s/g,"");if(e=a.match(/^[\+\-]?\d+(\.\d+)?|[\+\-]\d+(\.\d+)?/g)){for(l=0;l<e.length;l+=1)g+=Number(e[l])||0;g*=j}if(e=a.match(/^[\+\-]?(\$[a-z]+)|[\+\-](\$[a-z]+)/g))for(l=
0;l<e.length;l+=1)v+=b[e[l]]||0;if(e=a.match(/^[\+\-]?\$\d+(\.\d+)?|[\+\-]\$\d+(\.\d+)?/g))for(l=0;l<e.length;l+=1)v=v+Number(e[l].replace("$",""))||0;return g+v},i=function(a){var j=this.__state.annotationGroupsById;(a=j&&j[a])&&a.wrapper&&a.wrapper.show()},G=function(a){var j=this.__state.annotationGroupsById;(a=j&&j[a])&&a.wrapper&&a.wrapper.hide()},Q,o;Q=function(a,j,e,b){this.options=a;this.chart=e;this.attrs={};this.css={};this.bounds={};this.shared=j;this.snaps=b||{};this.id=a.id||"";this.items=
[];this.setup();this.scale()};X(Q.prototype,{scaleImageX:1,scaleImageY:1,scaleText:1,scaleValue:1,scaleValueComplement:1,scaleX:1,scaleY:1});Q.prototype.setup=function(){var a=this.options;this.isBelow=p(a.showbelow,a.showbelowchart,this.shared.showbelow)!="0";this.useTracker=!this.isBelow&&this.chart.trackerGroup&&this.shared.useTracker};Q.prototype.scale=function(){var a=this.options,j=this.chart,e=this.shared,b=this.bounds,g=this.snaps,v=e.rootxscale,l=e.rootyscale,ha=b.xs=s(a.xscale,e.xscale,
100)/100,i=b.ys=s(a.yscale,e.yscale,100)/100,f,h,d;this.scaleText*=i;this.scaleImageX*=ha;this.scaleImageY*=i;if(p(a.autoscale,e.autoscale)!="0")ha=s(a.origw,e.origw),i=s(a.origh,e.origh),ha=j.chartWidth/ha,i=j.chartHeight/i,j=p(a.constrainedscale,e.constrainedscale)!="0",f=ha<i?ha:i,h=j?f:ha,d=j?f:i,this.scaleValue*=f,this.scaleValueComplement*=j?f:ha<i?i:ha,this.scaleX*=h,this.scaleY=this.scaleX*d,b.xs*=h,b.ys*=d,v*=h,l*=d,p(a.scaletext,e.scaletext)=="1"&&(this.scaleText*=d),p(a.scaleimages,e.scaleimages)==
"1"&&(this.scaleImageX*=h,this.scaleImageY*=d);b.x=T(p(a.x,a.xpos),v,0,g)+s(a.grpxshift,e.grpxshift,0);b.y=T(p(a.y,a.ypos),l,0,g)+s(a.grpyshift,e.grpyshift,0);this.xshift=s(a.xshift,e.xshift,0);this.yshift=s(a.yshift,e.yshift,0)};Q.prototype.draw=function(){var a=this.chart,j=this.options,e=this.bounds,b=this.items,g;if(!this.wrapper)this.wrapper=a.renderer.g("annotations").attr({zIndex:this.isBelow?0.5:6}).add();for(this.wrapper.attr({x:0,y:0,visibility:j.visible=="0"?"hidden":""}).translate(e.x,
e.y);e=b.unshift();)e.destroy();if(j=j.items){e=0;for(g=j.length;e<g;e+=1)b.push((new o(a,j[e],this)).draw())}return this};Q.prototype.destroy=function(){for(var a=this.wrapper,j=this.items,e;e=j.shift();)e.destroy();if(a)this.wrapper=a.destroy()};o=function(a,j,e){var b=!1,g;this.chart=a;this.options=j;this.group=e;this.args=[];this.attrs={};this.attrsTracker={};this.style={};this.bounds={};this.type=j.type&&j.type.toLowerCase&&j.type.toLowerCase();for(g in o.eventNames)typeof j[g]==="function"&&
(this[g]=j[g],b=!0);this.hasEvents=b;if(typeof j.onload==="function")this.onload=j.onload;this.scale();this.setup()};o.prototype.getAbsoluteBounds=function(){var a=this.bounds,j=a.x1,e=a.y1,b=a.x2,g=a.y2,v=va(j,b),l=va(e,g),j=Y(j,b)-v,e=Y(e,g)-l;return{x:v,width:j,y:l,height:e,r:a.r,unscaled:{width:j/a.xs,height:e/a.ys}}};o.prototype.scale=function(){var a=this.group,j=a.bounds,e=this.bounds,b=this.options,g=a.snaps,v=p(b.x,b.xpos),l=p(b.y,b.ypos),i=p(b.tox,b.toxpos),n=p(b.toy,b.toypos),f=e.xs=j.xs,
j=e.ys=j.ys,h=s(b.xshift,a.xshift,0),d=s(b.yshift,a.yshift,0);this.hasDimensionY=this.hasDimensionX=this.hasDimension=!0;e.x1=T(v,f,0,g)+h;i===void 0?(this.hasDimensionX=this.hasDimension=!1,e.x2=e.x1):e.x2=T(i,f,0,g)+h;e.y1=T(l,j,0,g)+d;n===void 0?(this.hasDimensionY=this.hasDimension=!1,e.y2=e.y1):e.y2=T(n,j,0,g)+d;e.r=s(b.radius,0)*a.scaleValue};o.prototype.setup=function(){var a=this.options,b=this.group,e=b.options,g=this.attrs,oa=this.style,v=b.scaleValue,l=s(e.fillalpha,e.alpha,100),i=this.fillAlpha=
p(a.fillalpha,a.alpha,l),n=this.fillColor=p(a.fillcolor,a.color,e.color,"#ff0000"),f=this.fillPattern=p(a.fillpattern&&a.fillpattern.toLowerCase&&a.fillpattern.toLowerCase(),e.fillpattern&&e.fillpattern.toLowerCase&&e.fillpattern.toLowerCase()),h=a.showborder?a.showborder=="1":xa(a.bordercolor),d=this.borderAlpha=s(a.borderalpha,a.alpha,e.borderalpha,l),l=this.dashed=a.dashed=="1";this.link=p(a.link,e.link);this.shadow=p(a.showshadow,e.showshadow)=="1";g.stroke=h?la(p(a.bordercolor,n),d):"none";g["stroke-linecap"]=
"round";i={FCcolor:{gradientUnits:"objectBoundingBox",color:n,alpha:i,ratio:p(a.fillratio,e.fillratio),angle:360-s(a.fillangle,0),radialGradient:f==="radial"}};g.fill=i;g["stroke-width"]=h?s(a.borderthickness,a.thickness,2)*v:0;if(l)g.dashstyle=Z(a.dashlen*v,a.dashgap*v,g["stroke-width"]);if(this.link)oa.cursor="pointer",oa._cursor="hand";this.useTracker=b.useTracker;this.toolText=ta(p(a.tooltext,e.tooltext));(this.useTracker||this.link||this.toolText)&&X(this.attrsTracker,{isTracker:+new Date,stroke:ba,
fill:ba})};o.prototype.draw=function(){var a=this,j=a.chart,e=a.type,g=a.attrs,i=a.style,v=j.renderer,e=o.types[e]&&o.types[e].call&&o.types[e].call(a),l=e==="image",p=e==="text",s=l||p,f=a.link||a.toolText,h=a.wrapper,d=a.tracker,r=!1,c,D,m=o.eventNames,u,k;if(e){if(h)if(h.elemType!==e)h=h.destroy();else if(a.hasEvents)for(u in m)if((k=a[u])&&k.eventAttached)I(D.element,m[u],k),k.eventAttached=!1;h?h.attr(g).css(i):(h=a.wrapper=v[e].apply(j.renderer,a.args).attr(g).css(i).add(a.group.wrapper),h.elemType=
e,r=!0);a.shadow&&!a.shadowAdded&&!l&&!p?(i={opacity:Y(a.borderAlpha,g.fill.FCcolor.alpha)/100},a.shadowAdded=!0,h.shadow(i,void 0,i)):(a.shadowAdded=!1,(c=h.shadows)&&fa(c,function(a){h.safeRemoveChild(a)}));p&&h.textBound();if(f){if(a.useTracker){if(!d)d=a.tracker=s?v.rect(0,0,0,0,0):v[e].apply(j.renderer,a.args);d.attr(g).attr(a.attrsTracker);d.added||d.add(j.trackerGroup)}a.toolText&&a.createTooltip()}else d&&(d=d.destroy());D=a.tracker||h;if(a.link)D.on("click",function(){j.options.instanceAPI.linkClickFN.call(a)});
if(a.hasEvents)for(u in m)if((k=a[u])&&!k.eventAttached)b(D.element,m[u],k,a),k.eventAttached=!0;l||(d&&s&&d.attr(h.getBBox()),r&&a.onload&&a.onload(g))}return a};o.prototype.createTooltip=function(a){var b=this.wrapper,e=this.chart,g=e.plotLeft,i=e.plotTop,v,l,p,s,f,h=!1;if(v=e.tooltip)a||(a=this.tracker||b),l={tooltipPos:[20,20],series:{},svgElm:b.svgElm,point:this,getLabelConfig:na},p=function(){v.refresh(l)},s=function(){v.hide()},a.on("mousemove",function(a){l.tooltipPos[0]=(a.layerX||a.x)-g;
l.tooltipPos[1]=(a.layerY||a.y)-i;h&&f&&(f=clearTimeout(f));h=!1;f?(f=clearTimeout(f),f=setTimeout(p,150)):(v.refresh(l),f=-2)}).on("mouseout",function(){f=clearTimeout(f);h=!0;f=setTimeout(s,200)})};o.prototype.destroy=function(){var a=this.wrapper;if(a)this.tracker&&this.tracker.destroy(),this.wrapper=a.destroy()};o.eventNames={onmouseover:z?"touchstart":"mouseover",onmouseout:"mouseout",onmousemove:z?"touchmove":"mousemove",onclick:"click"};o.textAlignOptions={left:"left",right:"right",center:"center"};
o.textVerticalAlignOptions={top:"top",middle:"middle",bottom:"bottom"};o.textRotationOptions={0:"0",1:"270",right:"90",left:"270"};o.types={rectangle:function(){var a=this.args,b=this.getAbsoluteBounds(),e=b.width*0.5;if(b.r>e)b.r=e;a[0]=b.x;a[1]=b.y;a[2]=b.width;a[3]=b.height;a[4]=b.r;return"rect"},line:function(){var a=this.options,b=this.group.scaleValue,e=this.attrs,g=this.bounds;this.args[0]=["M",g.x1,g.y1,"L",g.x2,g.y2];e.stroke=la(this.fillColor,this.fillAlpha);e["stroke-width"]=s(a.thickness,
2)*b;e["stroke-width"]<sa&&(this.attrsTracker["stroke-width"]=sa);this.attrsTracker.dashstyle="solid";return"path"},polygon:function(){var a=this.args,b=this.options,e=this.bounds;a[0]="poly_"+s(b.sides,5);a[1]=e.x1;a[2]=e.y1;a[3]=e.r;a[4]={startAngle:s(b.startangle,0)*V};return"symbol"},circle:function(){var a=this.args,b=this.attrs,e=this.options,g=this.bounds,i=this.chart.chartWidth,v=this.chart.chartHeight,l=this.group.scaleValueComplement,n=ya(s(e.startangle,0),s(e.endangle,360)),o=g.r,f,h;if(!p(e.radius))g.r=
i<v?i*g.xs:v*g.ys,g.r=o=g.r*0.3;e=s(e.yradius,o/l)*l;if(!this.fillPattern)b.fill.FCcolor.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern==="radial")b.fill.FCcolor.cx=b.fill.FCcolor.cy=0.5;if(!(n.angle%360)&&o===e)return a[0]=g.x1,a[1]=g.y1,a[2]=g.r,"circle";n.angle%360||(n.start-=0.0010);b=this.chart.renderer.getArcPath;f=n.start*V;i=n.end*V;n=n.angle*V;v=g.x1;l=g.y1;g=v+qa(f)*o;f=l+wa(f)*e;h=v+qa(i)*o;i=l+wa(i)*e;o=b(v,l,g,f,h,i,o,e,0,n>=ca?1:0);o.unshift("M",g,f);o.push("Z");a[0]=
o;return"path"},arc:function(){var a=this.options,b=this.args,e=this.attrs,i=this.bounds,n=this.chart.chartWidth,v=this.chart.chartHeight,l=this.group.scaleValue,o=ya(s(a.startangle,0),s(a.endangle,360)),z=o.start,f=o.end;if(!p(a.radius))i.r=n<v?n*i.xs:v*i.ys,i.r*=0.3;i.innerR=s(a.innerradius,i.r*0.8/l)*l;if(i.innerR>i.r)i.innerR+=i.r,i.r=i.innerR-i.r,i.innerR-=i.r;!(o.angle%360)&&!g&&(f+=0.5,z-=0.5);if(!this.fillPattern)e.fill.FCcolor.radialGradient=!0,this.fillPattern="radial";if(this.fillPattern===
"radial")e.fill.FCcolor.cx=e.fill.FCcolor.cy=0.5;b[0]=i.x1;b[1]=i.y1;b[2]=i.r;b[3]=i.innerR;b[5]=z*V;b[4]=f*V;return"arc"},text:function(){var a=this.chart,b=this.args,e=this.style,g=this.attrs,i=this.group,v=this.bounds,l=this.options,n=this.getAbsoluteBounds(),z=p(l.align,i.options.textalign,"center").toLowerCase(),f=p(l.valign,i.options.textvalign,"middle").toLowerCase(),h=ta(p(l.text,l.label)),d=this.chart&&this.chart.renderer&&this.chart.renderer.smartLabel,r=p(l.wrap,i.options.wraptext)=="1",
c,D,m=p(l.rotatetext,i.options.rotatetext,"0").toLowerCase(),u=o.textRotationOptions[m],k=u!="0",m=k?"x":"y",k=k?"y":"x",a=a.options.orphanStyles,q=X({},a.defaultStyle.style||{}),F=a[i.id.toLowerCase()]||za,a=F.style.color,F=X(q,F.style),t=parseFloat(F.fontSize),q=u=="90"?-1:1,da=p(l.font,i.options.font,F.fontFamily),i=s(l.fontsize,i.options.fontsize,t)*i.scaleText;r&&(c=s(l.wrapwidth,this.hasDimensionX?n.width/v.xs:void 0),D=s(l.wrapheight,this.hasDimensionY?n.height/v.ys:void 0),c&&(c*=v.xs),D&&
(D*=v.ys));e.fontFamily=da;e.fontWeight=p(l.bold,l.isbold)=="1"?"bold":"normal";if(p(l.italic,l.isitalic)=="1")e.fontStyle="italic";if(l.bgcolor)e.backgroundColor=ra(l.bgcolor);if(l.bordercolor)e.borderColor=ra(l.bordercolor),e.border="1px solid "+e.borderColor;e.color=l.fontcolor?g.fill=ra(l.fontcolor):ra(a||g.fill.FCcolor.color);e.fontSize=i+"px";i==t?e.lineHeight=F.lineHeight:M(e);g.align=o.textAlignOptions[z]||"center";g.rotation=parseInt(u,10);d.setStyle(e);e=d.getSmartText(h,c,D,!1);switch(o.textVerticalAlignOptions[f]||
"middle"){case "top":n[m]+=(i-e.height)*q;break;case "bottom":n[m]+=i*q;break;default:n[m]+=(i-e.height*0.5)*q}g.align==="left"?n[k]+=s(l.leftmargin,0):g.align==="center"&&(n[k]+=s(l.leftmargin,0)*0.5);b[0]=e.text;b[1]=n.x;b[2]=n.y;delete g.stroke;delete g["stroke-weight"];return"text"},image:function(){var a=this,b=a.chart,e=a.style,g=b.chartWidth,i=b.chartHeight,b=a.options,n=a.attrs,l=a.args,o=xa(b.url),z=a.group.scaleImageX*p(Number(b.xscale),100)/100,f=a.group.scaleImageY*p(Number(b.yscale),
100)/100,h=a.getAbsoluteBounds(),d={width:1,height:1},r;if(!o)return l[0]=h.x,l[1]=h.y,l[2]=h.width,l[3]=h.height,l[4]=h.r,"rect";r=new Image;r.onload=function(){d=S("none","top","left",100,0,g,i,r);delete d.x;delete d.y;d=X(d,{width:(a.hasDimensionX?h.unscaled.width:d.width)*z,height:(a.hasDimensionY?h.unscaled.height:d.height)*f});setTimeout(function(){var f,h;if(f=a.wrapper)f.attr(d),(h=a.tracker)&&h.attr(f.getBBox()),f.css({opacity:e.opacity=Y(s(a.fillAlpha,a.borderAlpha),a.borderAlpha)/100});
a.onload&&a.onload(d)},0)};r.src=o;l[0]=o;l[1]=h.x;l[2]=h.y;l[3]=(a.hasDimensionX?h.unscaled.width:d.width)*z;l[4]=(a.hasDimensionY?h.unscaled.height:d.height)*f;e.opacity=Y(s(a.fillAlpha,a.borderAlpha),a.borderAlpha)/100;delete n.stroke;delete n.fill;delete n["stroke-linecap"];return"image"}};n.Highcharts.Chart.prototype.callbacks.unshift(function(a,b){var e=b.chartInstance,g=e.__state,i=b.dataObj||{},n=i.annotations,l=b.hcJSON,o={},z,f;if(!b.drawAnnotations||!e.dataReady()||!i.chart||!(i.chart.showannotations!=
"0"&&n&&n.groups&&n.groups.length)){if(!l||!l.annotations)return;n=l.annotations;if(n.options)o=n.options}else delete n.id;if(!g.annotationStores)g.annotationStores=[];g.annotationStores.push(e=n.id||"annotations");e=a[e]=[];o=X({showbelow:p(n.showbelow,n.showbelowchart),autoscale:n.autoscale,scaletext:n.scaletext,scaleimages:n.scaleimages,constrainedscale:n.constrainedscale,origw:p(n.origw,i.chart.origw,a.chartWidth),origh:p(n.origh,i.chart.origh,a.chartHeight),xshift:n.xshift,yshift:n.yshift,grpxshift:n.grpxshift,
grpyshift:n.grpyshift,xscale:n.xscale,yscale:n.yscale,rootxscale:s(n.xscale,100)/100,rootyscale:s(n.yscale,100)/100},o);if(b.snapLiterals){z=b.snapLiterals;i={};for(f in z)i["$"+f]=i["+$"+f]=z[f],i["-$"+f]=z[f]*-1;z=i}for(i=0;i<n.groups.length;i+=1)e.push(f=(new Q(n.groups[i],o,a,z)).draw()),f.id&&g.annotationGroupsById&&!a.renderer.forExport&&(g.annotationGroupsById[f.id]&&g.annotationGroupsById[f.id].destroy(),g.annotationGroupsById[f.id]=f)});aa.addEventListener("rendered",function(a,b){if(b.renderer===
"javascript"){var e=a.sender,g=e.jsVars||{},n=g.instanceAPI;if(!g.hcObj||!n||!n.drawAnnotations)delete e.showAnnotation,delete e.hideAnnotation;else{if(!e.showAnnotation)e.showAnnotation=e.ref.showAnnotation=i;if(!e.hideAnnotation)e.hideAnnotation=e.ref.hideAnnotation=G}}});aa.addEventListener("Initialized",function(a){var a=a.sender,b=a.__state;if(a.options.renderer==="javascript")b.annotationGroupsById={}});aa.addEventListener("Disposed",function(a){if(a.sender.options.renderer==="javascript"){var b=
a.sender,a=b.__state,b=b.jsVars.hcObj,e,g,i,n;for(n=a.annotationStores&&a.annotationStores.length||0;n--;){i=a.annotationStores[n];if(e=b&&b[i])for(;g=e.shift();)g.destroy();delete a[i]}}})}]);
FusionCharts(["private","modules.renderer.highcharts-maps",function(){var aa=this,n=aa.hcLib,$=n.chartAPI,fa=document,b=n.pluck,I=n.imprint,z=n.extend2,g=n.pluckNumber,sa=n.pluckFontSize,ba=n.placeLegendBlockRight,va=n.placeGLegendBlockRight,Y=n.placeGLegendBlockBottom,wa=n.placeLegendBlockBottom,qa=n.HCstub,ca=z(n.defaultPaletteOptions,{foregroundcolor:"333333",foregroundalpha:"100",foregrounddarkcolor:"111111",foregrounddarkalpha:"100",foregroundlightcolor:"666666",foregroundlightalpha:"100",backgroundlightcolor:"FFFFFF",
backgroundlightalpha:"100",backgroundlightangle:90,backgroundlightratio:"",backgroundcolor:"FFFFCC",backgroundalpha:"100",backgrounddarkcolor:"ffcc66",backgrounddarkalpha:"100",backgrounddarkangle:270,backgrounddarkratio:"",shadow:1}),V=n.setLineHeight,X=n.getValidValue,p=n.parseUnsafeString,s=n.getFirstColor,la=n.graphics.convertColor,Z=n.Highcharts,xa=Z.extend,ta=Z.isIE,S=Z.hasTouch,ra=Z.isWebKit,M=Z.hasSVG,za=Z.seriesTypes,na=n.FC_CONFIG_STRING,ya="rgba(192,192,192,"+(M?1.0E-6:0.0020)+")",T=fa.documentMode===
8?"visible":"",i=Math,G=i.min,Q=i.max,o=i.ceil,fa=!/fusioncharts\.com$/i.test(location.hostname),a=function(a,h){return h?xa(a.FCcolor,h):{FCcolor:a}},j=function(a){return a&&a.replace(/^#?([a-f0-9]+)/ig,"#$1")||"none"},e=function(){return{point:this}},U=function(a,h){var d,b;this.index=h;for(b in a)d=ca[a[b]],this[b]=d instanceof Array?d[h]:d},oa={right:function(a,b){return b},left:function(a,b){return a-b},center:function(a,b){return G(b,a-b)*2}},v={top:function(a,b){return b},middle:function(a,
b){return G(b,a-b)*2},bottom:function(a,b){return a-b}},l=function(a,b,d){function e(){var a=this.entityPathMap,c=this.data,f=c&&c.length||0,d=this.items,k=b.options.instanceAPI,m;if(b.options.chart.emulateFlashGutter){var k={startX:0,startY:0,endY:k.baseHeight*k._scaleFactor,endX:k.baseWidth*k._scaleFactor},g=this.group;this.chartObj.renderer.path(["M",k.startX,k.startY,"L",k.endX,k.endY]).add(g).attr({"stroke-width":1,stroke:la("FFFFFF","0")})}for(;f--;)m=c[f],k=m.id&&m.id.toLowerCase(),delete m.outlines,
delete m.label,delete m.shortlabel,delete m.labelposition,delete m.labelalignment,delete m.labelconnectors,k!==void 0&&a[k]&&(d[k]=new ha(I(m,a[k]),this.chartObj,k,this.group));for(m in a)d[m]||(d[m]=new ha(a[m],b,m,this.group))}function c(){var a=this.items,c=[],f,b;i.push({id:"entityLabels",items:c});for(b in a)(f=a[b].getLabelObject())&&c.push(f)}var g=b.options.instanceAPI,m=g.getEntityPaths(),u=g.hcJSON,k=g._scaleFactor,q=b.options[na],j=q._captionBlock,j=/bottom/.test(j.position)?0:j.height,
i;q._labelBaseWidth=g.baseWidth+2*b.plotLeft/k;q._labelBaseHeight=g.baseHeight+(2*b.plotTop-j)/k;q._labelXOffset=b.plotLeft/k;q._labelYOffset=(b.plotTop-j)/k;if(m&&b){if(!u.annotations)u.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:b.plotLeft?b.plotLeft:0,grpyshift:b.plotTop?b.plotTop:0,xscale:(g._scaleFactor?g._scaleFactor:1)*100,yscale:(g._scaleFactor?g._scaleFactor:1)*100,options:{useTracker:!0},groups:[]};i=u.annotations.groups;this.entityPathMap=m;this.data=a;this.chartObj=b;this.items=
{};this.group=d||b.seriesGroup;e.call(this);c.call(this);this.drawLabels=c;this.drawTrackers=function(){var a=this.items,c;for(c in a)a[c].drawTracker()};this.destroy=function(){var a=this.items,c;for(c in a)a[c].destroy();delete this.entityPathMap;delete this.data;delete this.chartObj;delete this.items;delete this.group};this.init=e}},ha=function(f,h,d,r){function c(){var a=this.chart.renderer,c=this.options.outlines,f=this.group,b,d;for(b=c&&c.length||0;b--;)d=c[b],this.svgElems[b]={},this.svgElems[b].graphic=
a.path(d).scale(Y).add(f).attr(B).shadow(Z,ha,L);return this}function j(){}function m(){if(h.hoverPoint)n.raiseEvent.apply(n,h.hoverEntityEventArgs),delete h.hoverEntityEventArgs,h.hoverEntity&&h.hoverEntityAttr&&h.hoverEntity.attr(h.hoverEntityAttr),delete h.hoverEntity,delete h.hoverEntityAttr,h.hoverPoint=null}if(f&&h&&d!==void 0){this.chart=h;this.options=f;this.group=r;this.id=d;this.originalId=f.origId;this.isVisible=!0;this.svgElems={};this.connectorElem={};var u=h.options,k=u.instanceAPI,
q=h.renderer,d=u.entities,l=d.dataLabels.style,t=d.valuesForMarkers?null:f.cleanValue,da=t===null?void 0:t,s=b(f.displayvalue,d.includeNameInLabels?d.useShortName?f.shortLabel:f.label:""),t=this.formattedValue=f.formattedValue||"",z=d.labelSepChar,x=g(f.showtooltip,d.showTooltip),A=this.toolText=x?p(b(f.tooltext,(d.useSNameInTooltip?f.shortLabel:f.label)+(isNaN(da)?"":d.tooltipSepChar+t))):"",K,y,w,G=g(f.showlabel,d.showLabels),I=b(f.bordercolor,d.borderColor),C=b(f.borderalpha,d.borderAlpha);K=d.scaleBorder===
1;var H=g(f.borderthickness,d.borderThickness),U=b(f.labelconnectorcolor,d.connectorColor),X=b(f.labelconnectoralpha,d.connectorAlpha),V=b(f.font,l.fontFamily),E=g(parseInt(f.fontsize,10),parseInt(l.fontSize,10)),R=b(f.fontcolor,l.color),ia=g(f.labelpadding,d.labelPadding),$=d.hoverOnEmpty,fa=g(f.usehovercolor,$?d.useHoverColor:isNaN(da)?0:d.useHoverColor),ba=g(f.hoverborderthickness,d.hoverBorderThickness),ma=g(f.fontbold,0),N=f.link,Z=d.shadow,ha=r.shadowGroup,l=!ta||M,Y=k._scaleFactor/d.baseScaleFactor;
y=k._strokeWidth;var ca=(l?d.baseScaleFactor:1)*y,ua=d.hiddenEntityFillObject||(d.hiddenEntityFillObject={fill:a({color:d.hiddenEntityColor,alpha:d.hiddenEntityAlpha})}),B,L,u=u[na],ka=u._labelBaseWidth,ea=u._labelBaseHeight,ga=u._labelXOffset,O=u._labelYOffset;l?(H=K?H*ca:H/Y)&&ra&&(H=o(H)):H=K?H*y:H;ba=ba===void 0?H:K?H*ca:ba/Y;if(b(f.color,f.alpha,f.angle,f.ratio)!==void 0)u=b(f.color,d.fillColor),K=b(f.alpha,d.fillAlpha),l=b(f.angle,d.fillAngle),y=b(f.ratio,d.fillRatio),w=a({color:u,alpha:K,angle:l,
ratio:y});else{if(!d.fillColorObject)d.fillColorObject=a({color:b(d.fillColor),alpha:b(d.fillAlpha),angle:b(d.fillAngle),ratio:b(d.fillRatio)});if(!d.emptyColorObject)d.emptyColorObject=a({color:b(d.emptyEntityColor),alpha:b(d.emptyEntityAlpha),angle:b(d.emptyEntityAngle),ratio:b(d.emptyEntityRatio)});w=isNaN(da)?d.emptyColorObject:d.fillColorObject;u=w.FCcolor.color;K=w.FCcolor.alpha;l=w.FCcolor.angle;y=w.FCcolor.ratio}A===""&&(x=0);B={stroke:la(I,C),"stroke-width":H,fill:this.fillColor=w};I=K.split(",");
if(Z&&!ha)ha=r.shadowGroup=q.g("shadow-group").add(r);H&&I.push(C);L={opacity:Q.apply(i,I)/100};if(fa){if(b(f.hovercolor,f.hoveralpha,f.hoverangle,f.hoverratio)!==void 0)u=b(f.hoverfillcolor,f.hovercolor,d.hoverFillColor),K=b(f.hoverfillalpha,f.hoveralpha,d.hoverFillAlpha),l=b(f.hoverfillangle,f.hoverangle,d.hoverFillAngle),y=b(f.hoverfillratio,f.hoverratio,d.hoverFillRatio),r=a({color:u,alpha:K,angle:l,ratio:y});else{if(!d.hoverColorObject)d.hoverColorObject=a({color:d.hoverFillColor,alpha:d.hoverFillAlpha,
angle:d.hoverFillAngle,ratio:d.hoverFillRatio});r=d.hoverColorObject}this.hoverColor=r}!f.displayvalue&&d.includeValueInLabels&&!isNaN(da)&&(s=s===void 0?t:s+z+t);this.value=da;this.addMouseGestures=function(){var a=this,c=a.options,b=a.svgElems,f,d,g,q=x&&h.tooltip,r={"stroke-width":ba,fill:a.hoverColor},u={"stroke-width":H,fill:a.fillColor},i={value:a.value,label:c.label,shortLabel:c.shortLabel,originalId:a.originalId||a.id,id:a.id},l={value:a.value,lName:c.label,sName:c.shortLabel,id:a.originalId||
a.id};if(!isNaN(da)||$)for(f in b)c=k._translateX?k._translateX:0,d=k._translateY?k._translateY:0,g=b[f].pointProxy={tooltipPos:[c,d],series:{},_fmEntity:a,svgElm:b[f].tracker.svgElm,tracker:b[f].tracker,toolText:A,getLabelConfig:e,onMouseOut:m,firePointEvent:j,onClick:function(a){aa.raiseEvent("entityclicked",i,k.chartInstance,a);N!==void 0&&k.linkClickFN.call({link:N})}},N!==void 0&&b[f].tracker.css({cursor:"pointer",_cursor:"hand"}),b[f].tracker.on("click",g.onClick).on(S?"touchstart":"mouseover",
function(c){var b=a.chart,f=b.plotLeft,d=b.plotTop,h;return function(e){m();e.type==="touchstart"&&g.onClick.apply(this,arguments);if(q){ta?(c.tooltipPos[0]=(e.layerX||e.x||e.clientX||e.offsetX||e.originalEvent&&e.originalEvent.layerX)-f+20,c.tooltipPos[1]=(e.layerY||e.y||e.clientY||e.offsetY||e.originalEvent&&e.originalEvent.layerY)-d-15):(c.tooltipPos[0]=(e.layerX||e.x||e.offsetX||e.clientX||e.originalEvent&&e.originalEvent.layerX)-f+20,c.tooltipPos[1]=(e.layerY||e.y||e.offsetY||e.clientY||e.originalEvent&&
e.originalEvent.layerY)-d-15);if(S&&(c.tooltipPos[0]<=0||c.tooltipPos[1]<=0))h=h||c.tracker.getBBox(),c.tooltipPos[0]=h.x*Y,c.tooltipPos[1]=h.y*Y;q.refresh(c,!1)}b.hoverPoint=c;b.hoverEntityEventArgs=["entityrollout",i,k.chartInstance,[k.chartInstance.id,"rollOut",l],e];if(fa&&a.isVisible)b.hoverEntity=c._fmEntity,b.hoverEntityAttr=u,a.attr(r);n.raiseEvent("entityrollover",i,k.chartInstance,[k.chartInstance.id,"rollOver",l],e)}}(g))};this.attr=function(a,c){var b=this.svgElems,f;for(f in b)b[f].graphic&&
b[f].graphic.attr(a,c)};this.draw=c;this.getLabelObject=function(){var a=this,c=a.options,b=a.chart.renderer,f=c.labelPosition,d=c.labelAlignment,h=c.labelConnectors,e=a.svgElems[0]&&a.svgElems[0].graphic,m,g;if(!G||!e||!s)return null;for(m=c=h&&h.length||0;m--;)g=h[m],a.connectorElem[m]=b.path(g).scale(Y).add(a.group).attr({stroke:la(U,X),"stroke-width":ca});f?(b=f[0],h=f[1]):(f=e.getBBox(),b=f.x+f.width/2,h=f.y+f.height/2);d?(f=d[0],d=d[1],f==="right"?b-=ia:f==="left"&&(b+=ia),d==="top"?h-=ia:d===
"bottom"&&(h+=ia)):(f="center",d="middle");return{x:b.toString(),y:h.toString(),wrapwidth:oa[f](ka,b+ga)-ia,wrapheight:v[d](ea,h+O)-ia,wrap:1,type:"text",align:f,valign:d,text:s,link:c?N:null,bgcolor:"",bordercolor:"",fontcolor:R,fontsize:parseFloat(E)/k._scaleFactor,font:V,bold:ma,onclick:function(){return a.svgElems[0].pointProxy.onClick.apply(this,arguments)},onmouseover:function(){var c=a.svgElems[0],c=c&&c.tracker.element[S?"ontouchstart":"onmouseover"],f=arguments[0],b=f.data;if(M)f.layerX=
b.args&&b.args[1],f.layerY=b.args&&b.args[2];return c&&c.apply(this,arguments)}}};this.translate=function(a,c){var b=this.svgElems,f;if(typeof a===OBJECTSTRING&&a!==null)c=a.y,a=a.x;for(f in b)b[f].graphic.translate(a,c),b[f].tracker.translate(a,c)};this.destroy=function(){var a=this.svgElems,c=this.connectorElem,b;for(b in a)a[b].destroy&&a[b].destroy();for(b in c)c[b].destroy&&c[b].destroy();delete this.value;delete this.formattedValue;delete this.toolText;delete this.fillColor;delete this.hoverColor;
delete this.chart;delete this.group;delete this.id;delete this.isVisible;delete this.svgElems;delete this.connectorElem;delete this.renderer;delete this.options};this.drawTracker=function(){var a=this.chart,c=a.renderer,b=this.options.outlines,f,d;for(f=b&&b.length||0;f--;)d=b[f],this.svgElems[f].tracker=c.path(d).scale(Y).add(a.trackerGroup).attr({isTracker:!0,stroke:"none",fill:ya,"stroke-width":1,visibility:T});this.addMouseGestures();return this};this.show=function(){var a=this.svgElems,c;this.isVisible=
!0;for(c in a)a[c].graphic&&a[c].graphic.attr(B)};this.hide=function(){var a=this.svgElems,c;this.isVisible=!1;for(c in a)a[c].graphic&&a[c].graphic.attr(ua)};c.call(this);d.hideEmptyEntities&&da===void 0&&this.hide()}},Ka=function(f,h){this.markerObjs={};this.shapeObjs={};this.markerElemObj={};this.connectors=[];this.options=f;this.chart=h;this.group=h.renderer.g("markers").add(h.seriesGroup);var d=h&&h.options&&h.options.instanceAPI,e=d.hcJSON,c={top:function(a,c,b){return{x:a.toString(),y:(c-b).toString(),
align:"center",valign:"top"}},left:function(a,c,b){return{x:(a-b).toString(),y:c.toString(),align:"right",valign:"middle"}},right:function(a,c,b){return{x:(a+b).toString(),y:c.toString(),align:"left",valign:"middle"}},bottom:function(a,c,b){return{x:a.toString(),y:(c+b).toString(),align:"center",valign:"bottom"}},center:function(a,c){return{x:a.toString(),y:c.toString(),align:"center",valign:"middle"}}},j;if(!e.annotations)e.annotations={id:"geo",showbelow:0,autoscale:0,grpxshift:h.plotLeft?h.plotLeft:
0,grpyshift:h.plotTop?h.plotTop:0,xscale:(d._scaleFactor?d._scaleFactor:1)*100,yscale:(d._scaleFactor?d._scaleFactor:1)*100,options:{useTracker:!0},groups:[]};j=e.annotations.groups;this.applyMarkers=function(){var a=this.chart,c=a.plotLeft,f=a.plotTop,d=a.options,a=d[na],h=d.instanceAPI,d=d.markers,e=this.markerObjs,r=this.shapeObjs,i=this.options.application,l=d.dataLabels.style.fontFamily,n=d.dataLabels.style.fontSize,s=d.dataLabels.style.fontColor,p=d.showTooltip,y=d.showLabels,w=d.labelPadding,
o=d.labelWrapWidth,v=d.labelWrapHeight,C=d.labelSepChar,H=d.tooltipSepChar,I=d.fillColor,Q=d.fillAlpha,M=d.fillRatio,E=d.fillAngle,R=d.startAngle,U=d.borderThickness,S=d.borderColor,T=d.borderAlpha,X=d.radius,V=d.autoScale?h._scaleFactor:1,N=i&&i.length,Y=[],$=[],ba=function(a){var c;if(a=r[a]){if(a.type==="polygon")a.sides<3?a.type="circle":a.startangle=R;else if(a.type==="arc")c=a.radius&&a.radius*V||X,a.radius=c,a.innerradius=a.innerradius&&a.innerradius*V||c*0.6;return a}else return null},fa=
{right:function(a,c){return c},left:function(a,c){return a-c},center:function(a,c){return G(c,a-c)*2}},ha={top:function(a,c){return c},middle:function(a,c){return G(c,a-c)*2},bottom:function(a,c){return a-c}},B,L,ka,ea,ga,O,W,Z;j.push({id:"markers",fillalpha:"100",items:Y});for(j.push({id:"markerlabels",items:$});N;N-=1)if(B=i[N-1],O=e[B.id&&B.id.toLowerCase()],O!==void 0){this.markerElemObj[B.id.toLowerCase()]=B;B._annotationIndex=Y.length;W=b(B.shapeid,O.shapeid,"circle").toLowerCase();L=parseFloat(B.scale);
ka=b(B.label,O.label,"");ga=b(B.labelpos,O.labelpos,"top");isNaN(L)?L=1:L<0?L=0:L>5&&(L=5);Z=B.formattedValue===void 0?"":B.formattedValue;ka=ka||"";ea=Z?ka+H+Z:ka;ka=Z?ka+C+Z:ka;L=g(B.radius,O.radius,X)*L*V||1.0E-4;B={x:O.x.toString(),y:O.y.toString(),fillcolor:b(B.fillcolor,B.color,I),fillalpha:b(B.fillalpha,B.alpha,Q),fillratio:b(B.fillratio,M),fillangle:b(B.fillangle,E),borderthickness:g(B.borderthickness,U),bordercolor:b(B.bordercolor,S),borderalpha:b(B.borderalpha,T),radius:L,tooltext:p?B.tooltext?
B.tooltext:ea:"",link:B.link,showshadow:g(B.showshadow,d.shadow),_markerLabel:ka,_markerId:O.id,onmouseover:function(a){var b=a.data,d=b.options,b=b.bounds,e=d._markerRollOverArgs;if(!e)e=d._markerRollOverArgs={x:b.x1/b.xs,y:b.y1/b.ys,scaledX:b.x1,scaledY:b.y1,chartX:c+b.x1,chartY:f+b.y1,id:d._markerId,label:d._markerLabel};aa.raiseEvent("markerrollover",e,h.chartInstance,a)},onmouseout:function(a){aa.raiseEvent("markerrollout",a.data.options._markerRollOverArgs,h.chartInstance,a)},onclick:function(a){aa.raiseEvent("markerclicked",
a.data.options._markerRollOverArgs,h.chartInstance,a)}};W==="triangle"?z(B,{type:"polygon",sides:3,startangle:R}):W==="diamond"?z(B,{type:"polygon",sides:4,startangle:R}):W==="arc"?z(B,{type:"arc",startangle:0,endangle:360,innerradius:L*0.6}):W==="circle"?B.type="circle":z(B,ba(W));if(B.type==="image")B.onload=function(a){var c=this.options,b=a.width,a=a.height,f=(Number(c.x)-b/(2*h._scaleFactor))*h._scaleFactor,c=(Number(c.y)-a/(2*h._scaleFactor))*h._scaleFactor,d;if(b&&a)for(d in{wrapper:1,tracker:1})this[d]&&
this[d].attr({x:f,y:c,width:b,height:a})};Y.push(B);if(y){W=B.labelpadding||w;ga=this.getLabelAttrs(ga,W,B);ea=ga.align;O=ga.valign;var ca=a._labelBaseWidth;L=a._labelBaseHeight;var la=a._labelXOffset;Z=a._labelYOffset;ca=o?o:fa[ea](ca,Number(ga.x)+la);O=v?v:ha[O](L,Number(ga.y)+Z);L=h._scaleFactor;ca>W&&(ca-=W);O>W&&(O-=W);$.push(z({type:"text"},{text:ka,tooltext:B.tooltext,x:ga.x,y:ga.y,align:ea,valign:ga.valign,wrap:1,wrapwidth:ca,wrapheight:O,fontsize:n/L,font:l,fontcolor:s}))}}};this.defineMarkersNShapes=
function(){var a=this.options.definition,c=this.options.shapes,b=a.length,f,d;if(a&&a.length){for(;b;b-=1)if(f=a[b-1],d=f.id.toLowerCase())this.markerObjs[d]=f;if(c&&c.length)for(b=c.length;b;b-=1)if(f=c[b-1],d=f.id.toLowerCase())this.shapeObjs[d]=f}};this.getConnectorJSON=function(a){var c=h.options.connectors,f=a.to,e=this.markerObjs[a.from.toLowerCase()],f=this.markerObjs[f.toLowerCase()],j=a.link,r=a.label,i=g(a.showtooltip,c.showTooltip),l=i?a.tooltext:"",n=b(a.thickness,c.thickness),D=b(a.color,
c.color),s=b(a.alpha,c.alpha),p=b(a.dashed,c.dashed),o=g(a.dashlen,c.dashLen),a=g(a.dashgap,c.dashGap),w;return!e||!f?null:(w={fromMarkerId:e.id,toMarkerId:f.id},{x:e.x,y:e.y,tox:f.x,toy:f.y,dashed:p,dashlen:o,dashgap:a,link:j,tooltext:i?l:"",thickness:n,color:D,alpha:s,label:r,showshadow:c.shadow,onmouseover:function(a){aa.raiseEvent("connectorrollover",w,d.chartInstance,a)},onmouseout:function(a){aa.raiseEvent("connectorrollout",w,d.chartInstance,a)},onclick:function(a){aa.raiseEvent("connectorclicked",
w,d.chartInstance,a)}})};this.drawConnectors=function(){var a=h.options.connectors,c=a.showLabels,b=this.options.connectors,f=b&&b.length,e=[],g=[],r;if(f){j.push({id:"connectors",fillalpha:"100",items:e});for(j.push({id:"connectorLabels",fillalpha:"100",items:g});f--;)if(r=b[f],r=this.getConnectorJSON(r))e.push(z({type:"line"},r)),r.label&&c&&g.push(z({type:"text"},{x:((Number(r.x)+Number(r.tox))/2).toString(),y:((Number(r.y)+Number(r.toy))/2).toString(),text:r.label,align:"center",valign:"middle",
font:a.font,fontsize:a.fontSize/d._scaleFactor,fontcolor:a.fontColor,bgcolor:a.labelBgColor,bordercolor:a.labelBorderColor,tooltext:r.showtooltip?r.tooltext:""}))}};this.getLabelAttrs=function(a,b,f,h,e){var g,r=a&&a.toLowerCase();c[r]||(r="center");a=Number(f.x);g=Number(f.y);f=h===void 0||e===void 0?f.radius||0:/^(top|bottom)$/ig.test(r)&&e*0.5||/^(left|right)$/ig.test(r)&&h*0.5||0;f=(Number(f)+Number(b))/d._scaleFactor;return c[r](a,g,f)};this.setMarkerVisibility=function(c,b){var f=this.chart,
f=f.options&&f.options.instanceAPI&&f.options.instanceAPI.chartInstance;if(f=(f.__state&&f.__state.annotationGroupsById).markers.items[b._annotationIndex]){if(!b._origFill)b._origFill=a({alpha:f.fillAlpha,color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio}),b._hideFill=a({alpha:"0",color:f.fillColor,angle:f.fillAngle,ratio:f.fillRatio});c?f.wrapper.attr({fill:b._origFill}):f.wrapper.attr({fill:b._hideFill})}};this.destroy=function(){delete this.markerObjs;delete this.shapeObjs;delete this.markerElemObj;
delete this.connectors;delete this.options;delete this.chart;this.group.destroy();delete this.group};this.defineMarkersNShapes();this.drawConnectors();this.applyMarkers()};xa(n.eventList,{entityrollover:"FC_Event",entityrollout:"FC_Event"});$("geo",{name:"(unknown)",revision:1,creditLabel:fa,standaloneInit:!1,charttopmargin:10,chartrightmargin:10,chartbottommargin:10,chartleftmargin:10,baseWidth:400,baseHeight:300,baseScaleFactor:1,defaultSeriesType:"geo",entities:{},chart:function(f,h){z(this.dataObj.chart,
{charttopmargin:this.dataObj.chart.maptopmargin,chartrightmargin:this.dataObj.chart.maprightmargin,chartbottommargin:this.dataObj.chart.mapbottommargin,chartleftmargin:this.dataObj.chart.mapleftmargin,animation:this.dataObj.chart.animation||"0"});var d=this.dataObj,e=qa(d,f,h,this),c=d.chart,i=e.chart,m=m=e[na],l=i.useRoundEdges=g(c.useroundedges)===1,k=l?1:0,l=l?0:1,q=i.use3DLighting=g(c.use3dlighting,1)===1,n=z({},e.tooltip.style),t=new U(this.colorPaletteMap,(c.palette>0&&c.palette<6?c.palette:
g(this.paletteIndex,1))-1),o=b(c.basefont,"Verdana"),pa=sa(c.basefontsize,10),v=b(c.basefontcolor,t.basefontcolor),x=sa(c.outcnvbasefontsize,pa),A=b(c.outcnvbasefont,o),K=x+"px",y=j(b(c.outcnvbasefontcolor,v)),w=b(c.bgcolor,c.canvasbgcolor,t.canvasbgcolor),G=b(c.bgalpha,c.canvasbgalpha,t.canvasbgalpha),I,C;pa+="px";v=j(v);this.realtimeEnabled&&this.postHCJSONCreation&&this.postHCJSONCreation.call(this,e);i.events.click=this.linkClickFN;m.numberFormatter=this.numberFormatter;z(m,{width:f,height:h,
showTooltip:g(c.showtooltip,this.showtooltip,1),tooltipSepChar:b(c.tooltipsepchar,", "),showValues:g(c.showvalues,this.showValues,1),showCanvasBG:b(c.showcanvasbg,1),useValuesForMarkers:g(c.usevaluesformarkers,0),outCanvasStyle:{fontFamily:A,color:y,fontSize:K},inCanvasStyle:{fontFamily:o,fontSize:pa,color:v}});I=V(m.outCanvasStyle);C=V(m.inCanvasStyle);m.trendStyle=m.outCanvasStyle;m.showCanvasBG=="0"&&(G="0");var H=b(c.bordercolor,t.plotbordercolor),M=b(c.fillcolor,t.plotfillcolor),S=b(c.fillalpha,
t.plotfillalpha),T=b(c.fillratio,t.plotfillratio),E=b(c.fillangle,t.plotfillangle),R=b(c.emptyentityfillcolor,c.emptyentitycolor,M);z(e,{chart:{emulateFlashGutter:g(c._emulateflashgutter,1)},title:{text:p(c.caption),offsetX:Number(c.captionxshift),offsetY:Number(c.captionyshift),position:b(c.captionposition,c.captionxshift!==void 0||c.captionyshift!==void 0?"top left":"top"),padding:g(c.captionpadding,10),style:{fontFamily:A,color:y,fontSize:x+3+"px",fontWeight:g(c.captionfontbold)===0?"normal":"bold"}},
subtitle:{text:p(c.subcaption),style:{fontFamily:A,color:y,fontSize:x+1+"px",fontWeight:g(c.subcaptionfontbold)===0?"normal":"bold"}},orphanStyles:{defaultStyle:{style:z({},m.inCanvasStyle)}},tooltip:{enabled:m.showTooltip!==0,style:{fontFamily:o,fontSize:pa,lineHeight:C,color:v,padding:g(c.tooltippadding,this.tooltippadding,4),backgroundColor:void 0,borderColor:void 0,border:void 0},backgroundColor:la(b(n.backgroundColor,c.tooltipbgcolor,t.tooltipbgcolor),b(c.tooltipbgalpha,"100")),borderColor:la(b(n.borderColor,
c.tooltipbordercolor,t.tooltipbordercolor),b(c.tooltipborderalpha,"100")),borderWidth:g(c.tooltipborderthickness,l),borderRadius:g(c.tooltipborderradius,k+1),shadow:g(c.showtooltipshadow,k)?{enabled:!0,opacity:g(Q(c.tooltipbgalpha,c.tooltipborderalpha),100)/100}:!1},legend:{itemStyle:{fontFamily:A,fontSize:K,lineHeight:I,color:y},itemHiddenStyle:{fontFamily:A,fontSize:K,lineHeight:I},enabled:g(c.showlegend,1),title:{text:p(c.legendcaption),style:{fontFamily:A,fontSize:K,lineHeight:I,color:y}},position:b(c.legendposition,
g(d.colorrange&&d.colorrange.gradient,0)===0?"right":"bottom"),backgroundColor:b(c.legendbgcolor,t.bgcolor),backgroundAlpha:b(c.legendbgalpha,"100"),borderColor:b(c.legendbordercolor,t.legendbordercolor),borderThickness:b(c.legendborderthickness,"1"),borderAlpha:b(c.legendborderalpha,"100"),shadow:g(c.legendshadow,1),allowDrag:g(c.legendallowdrag,0),scroll:{scrollBgColor:b(c.legendscrollbgcolor,"AAAAAA"),scrollBtnColor:b(c.legendscrollbtncolor,"BBBBBB"),scrollBarColor:b(c.legendscrollbarcolor,"CCCCCC")},
reversed:g(c.reverselegend,0),interactive:g(c.interactivelegend,0),minColor:R,lighting3d:q},markers:{dataLabels:{style:{fontFamily:b(c.markerfont,o),fontSize:g(c.markerfontsize,parseInt(pa,10)),fontColor:b(c.markerfontcolor,v)}},showTooltip:g(c.showmarkertooltip,m.showTooltip),showLabels:g(c.showmarkerlabels,c.showlabels,1),labelPadding:b(c.markerlabelpadding,"5"),labelWrapWidth:g(c.markerlabelwrapwidth,0),labelWrapHeight:g(c.markerlabelwrapheight,0),fillColor:b(c.markerfillcolor,c.markerbgcolor,
t.markerbgcolor),fillAlpha:b(c.markerfillalpha,t.markerbgalpha),fillAngle:b(c.markerfillangle,t.markerbgangle),fillRatio:b(c.markerfillratio,t.markerbgratio),fillPattern:b(c.markerfillpattern,t.markerbgpattern),borderThickness:b(c.markerborderthickness,1),borderColor:b(c.markerbordercolor,t.markerbordercolor),borderAlpha:g(c.markerborderalpha,t.markerborderalpha),radius:g(c.markerradius,7),labelSepChar:b(c.labelsepchar,", "),tooltipSepChar:m.tooltipSepChar,autoScale:g(c.autoscalemarkers,0),mapValueToRadius:g(c.mapmarkervaluetoradius,
0),startAngle:g(c.markerstartangle,90),maxRadius:g(c.maxmarkerradius,0.3*f),minRadius:g(c.minmarkerradius,0.02*f),applyAll:g(c.applyallmarkers,0),shadow:g(c.showmarkershadow,c.showshadow,0)},connectors:{thickness:g(c.connectorthickness,c.markerconnthickness,"2"),color:b(c.connectorcolor,c.markerconncolor,t.markerbordercolor),alpha:b(c.connectoralpha,c.markerconnalpha,"100"),dashed:g(c.connectordashed,c.markerconndashed,0),dashLen:g(c.connectordashlen,c.markerconndashlen,3),dashGap:g(c.connectordashgap,
c.markerconndashgap,2),font:b(c.connectorfont,c.markerconnfont,o),fontColor:b(c.connectorfontcolor,c.markerconnfontcolor,v),fontSize:g(c.connectorfontsize,c.markerconnfontsize,parseInt(pa,10)),showLabels:g(c.showconnectorlabels,c.showmarkerlabels,c.showlabels,1),labelBgColor:b(c.connectorlabelbgcolor,c.markerconnlabelbgcolor,t.plotfillcolor),labelBorderColor:b(c.connectorlabelbordercolor,c.markerconnlabelbordercolor,t.markerbordercolor),shadow:g(c.showconnectorshadow,c.showmarkershadow,c.showshadow,
0),showTooltip:g(c.showconnectortooltip,c.showmarkertooltip,m.showTooltip)},entities:{baseScaleFactor:this.baseScaleFactor,dataLabels:{style:{fontFamily:o,fontSize:pa,lineHeight:C,color:e.plotOptions.series.dataLabels.color=v}},fillColor:M,fillAlpha:S,fillRatio:T,fillAngle:E,borderColor:H,borderAlpha:b(c.borderalpha,this.borderAlpha,"100"),borderThickness:g(c.showborder,1)?g(c.borderthickness,1):0,scaleBorder:g(c.scaleborder,0),hoverFillColor:b(c.hoverfillcolor,c.hovercolor,t.plothoverfillcolor),
hoverFillAlpha:b(c.hoverfillalpha,c.hoveralpha,t.plothoverfillalpha),hoverFillRatio:b(c.hoverfillratio,c.hoverratio,t.plothoverfillratio),hoverFillAngle:b(c.hoverfillangle,c.hoverangle,t.plothoverfillangle),hoverBorderThickness:b(c.hoverborderthickness),emptyEntityColor:R,emptyEntityAlpha:b(c.emptyentityfillalpha,c.emptyentityalpha,S),emptyEntityRatio:b(c.emptyentityfillratio,c.emptyentityratio,T),emptyEntityAngle:b(c.emptyentityfillangle,c.emptyentityangle,E),connectorColor:b(c.labelconnectorcolor,
c.connectorcolor,v),connectorAlpha:b(c.labelconnectoralpha,c.connectoralpha,"100"),useHoverColor:g(c.usehovercolor,1),hoverOnEmpty:g(c.hoveronempty,1),labelPadding:g(c.labelpadding,5),showLabels:g(c.showlabels,1),includeNameInLabels:g(c.includenameinlabels,1),includeValueInLabels:g(c.includevalueinlabels,0),useSNameInTooltip:g(c.usesnameintooltip,0),useShortName:g(c.usesnameinlabels,1),labelSepChar:b(c.labelsepchar,", "),showTooltip:g(c.showentitytooltip,m.showTooltip),tooltipSepChar:m.tooltipSepChar,
valuesForMarkers:g(c.usevaluesformarkers,0),hideEmptyEntities:g(c.hideemptyentities,0),showHiddenEntityBorder:g(c.showhiddenentityborder,1),hiddenEntityColor:b(c.hiddenentitycolor,c.hiddenentityfillcolor,c.hiddenentityalpha||c.hiddenentityfillalpha?R:"ffffff"),hiddenEntityAlpha:b(c.hiddenentityalpha,c.hiddenentityfillalpha,0.0010),shadow:g(c.showshadow,this.defaultPlotShadow,t.shadow)},entitydef:{useSNameAsId:g(c.usesnameasid,0)}});if(c.tooltipcolor)e.tooltip.style.color=s(c.tooltipcolor);if(b(c.clickurl)!==
void 0)i.link=c.clickurl,i.style.cursor="pointer",ta&&(i.style._cursor="hand"),e.plotOptions.series.point.events.click=function(){i.events.click.call({link:c.clickurl})};z(i,{defaultSeriesType:this.defaultSeriesType,paletteIndex:t.index,borderRadius:g(c.canvasborderradius,0),borderColor:la(b(c.canvasbordercolor,t.canvasbordercolor),b(c.canvasborderalpha,t.canvasborderalpha)),borderWidth:g(c.showcanvasborder,l)?g(c.canvasborderthickness,1):0,backgroundColor:a({color:w,alpha:G,angle:b(c.bgangle,c.canvasbgangle,
t.canvasbgangle),ratio:b(c.bgratio,c.canvasbgratio,t.canvasbgratio)}),plotBorderColor:"#ffffff",plotBorderWidth:0,plotBackgroundColor:a({color:"#ffffff",alpha:0}),bgSWF:b(c.bgimage,c.bgswf),bgSWFAlpha:g(c.bgimagealpha,c.bgswfalpha,100),bgImageScale:g(c.bgimagescale,100),bgImageDisplayMode:b(c.bgimagedisplaymode,"none").toLowerCase(),logoURL:X(c.logourl),logoPosition:b(c.logoposition,"tl").toLowerCase(),logoAlpha:g(c.logoalpha,100),logoLink:X(c.logolink),logoScale:g(c.logoscale,100),logoLeftMargin:g(c.logoleftmargin,
0),logoTopMargin:g(c.logotopmargin,0)});m=i.bgImageDisplayMode;k=X(c.bgimagevalign,"").toLowerCase();l=X(c.bgimagehalign,"").toLowerCase();m=="tile"||m=="fill"||m=="fit"?(k!="top"&&k!="middle"&&k!="bottom"&&(k="middle"),l!="left"&&l!="middle"&&l!="right"&&(l="middle")):(k!="top"&&k!="middle"&&k!="bottom"&&(k="top"),l!="left"&&l!="middle"&&l!="right"&&(l="left"));i.bgImageVAlign=k;i.bgImageHAlign=l;this.parseStyles(e);V(e.title.style);V(e.subtitle.style);V(e.tooltip.style);e.plotOptions.series.allowPointSelect=
!0;this.parseExportOptions(e);this.preSeriesAddition&&this.preSeriesAddition(e,d,f,h);this.series&&this.series(d,e,this.name,f,h);this.postSeriesAddition&&this.postSeriesAddition(e,d,f,h);this.spaceManager(e,d,f,h);window.console&&window.FC_DEV_ENVIRONMENT&&window.console.log(e);return e},series:function(a,e){var d=this.numberFormatter,i=this.hcJSON.series,c=this.dataObj,j=e[na],m=c.colorrange,m=m&&m.color,l=e.legend,k=j.useValuesForMarkers?c.markers&&c.markers.application||[]:c.data,q={},s=function(a){for(var c,
b,f=v&&v.length||0;f--;)if(c=v[f],b=Number(c.maxvalue),c=g(c.minvalue,e.colorRange.scaleMin),a>=c&&a<=b)return f;return null},t=Infinity,p=-Infinity,o,v,x;l.type=c.colorrange&&c.colorrange.gradient==="1"?"gradient":"point";for(x=k&&k.length||0;x--;)o=k[x],value=o.value,o.cleanValue=d.getCleanValue(value),o.formattedValue=o.cleanValue!==null?d.dataLabels(value):void 0,o.origValue=value,o.cleanValue!==null&&(t=G(o.cleanValue,t),p=Q(o.cleanValue,p));t===Infinity&&(t=void 0);p===-Infinity&&(p=void 0);
e.colorRange=new n.colorRange({colorRange:c.colorrange,dataMin:t,dataMax:p,defaultColor:l.minColor,numberFormatter:d});x=(v=e.colorRange.colorArr)&&v.length||0;j._doNotShowLegend=!0;if(x>0){for(;x--;){o=v[x];if(j._doNotShowLegend&&(o.label!==""||o.label!==void 0))j._doNotShowLegend=!1;i.push({type:this.defaultSeriesType,showInLegend:!0,data:[],name:o.label,color:o.code,rangeMin:o.minvalue,rangeMax:o.maxvalue,allVisible:!0,allHidden:!1})}for(x=k&&k.length||0;x--;)if(o=k[x],d=s(g(o.value)),d!==null&&
(j=l.type==="gradient"?e.colorRange.getColorObj(o.value).code:m&&m[d]&&b(m[d].color,m[d].code),q[d]||(q[d]=[]),j))o.color=o.color?o.color:j,q[d].push(o);i=i.reverse();for(x in q)i[x]&&(i[x].data=q[x])}else i.push({type:this.defaultSeriesType,data:k||[]})},spaceManager:function(a,b,d,e){var c=a.chart,g=a[na];g.smartLabel=this.smartLabel;var m=c.spacingLeft,i=c.spacingTop,k=this.baseWidth,j=this.baseHeight;d-=c.spacingRight+m;var l=e-(c.spacingBottom+i),e=g._captionBlock=this.manageTitleSpace(a,b,n,
l),a=g._legendBlock=this.placeLegendBlock(a,b,d,l-e.height,e.isBottom?e.height:0),n=d-a.width,a=l-e.height-a.height,o,p;g.viewportWidth=n;g.viewportHeight=a;g.trackerTop=i;g.trackerLeft=m;n/a>k/j?(m=a/j,o=(n-m*k)/2,k=200/(j*m)):(m=n/k,p=(a-m*j)/2,k=200/(k*m));o=o?o:0;p=p?p:0;c.marginLeft+=o;c.marginRight+=o;c.marginTop+=p;c.marginBottom+=p;/bottom/i.test(e.position)||(p+=e.height,g.trackerTop+=e.height);this._scaleFactor=m;this._strokeWidth=k;this._translateX=o;this._translateY=p},placeLegendBlock:function(a,
b,d,e,c){var g=a.legend,i=a[na],j=g.position.toLowerCase(),k={position:j};if(b.chart.showlegend==="0"||i._doNotShowLegend)return k.height=0,k.width=0,k;if(j==="bottom"){if(k.height=g.type==="gradient"?Y(a,b,d,e):wa(a,b,d,e),k.width=0,c)g.y=-c}else d/=2,k.width=g.type==="gradient"?va(a,b,d,e):ba(a,b,d,e),k.height=0;return k},manageTitleSpace:function(a,b,d,e){var c=this.hcJSON,a=c.title,b=c.chart,c=c.subtitle,g=this.smartLabel,j=e/2,i=0,k=a.position.toLowerCase(),l=a.padding,n=!1,o=a.offsetX,p=a.offsetY,
s=0,v={},x,A,z;if(a.text===""&&c.text==="")return{height:0,position:k};if(!isNaN(o)||!isNaN(p))n=!0,o=isNaN(o)?0:o,p=isNaN(p)?0:p;x=a.text;if(x!==""){g.setStyle(a.style);A=g.getOriSize(x);if(A.width>d||A.height>j)A=g.getSmartText(x,d,j),a.text=A.text;s=A.height;i+=s}j-=i;x=c.text;if(x!==""){g.setStyle(c.style);A=g.getOriSize(x);if(A.width>d||A.height>j)A=g.getSmartText(x,d,j),c.text=A.text;i+=A.height}i+l>j?i=j:i+=l;/bottom/.test(k)?(d=e-i+l+g.getOriSize("Wqt").height,a.y=d,c.y=d+s,n?(a.y+=p,c.y+=
p,a.x=o,c.x=o):(b.marginBottom+=i,v.isBottom=!0)):n?(a.y=p,c.y=p+s,a.x=o,c.x=o):b.marginTop+=i;a.align=c.align=(z=k.match(/left|right/))&&z[0]||"center";v.height=n?0:i;v.position=k;return v},getEntityPaths:function(){return this.entities},redefineEntities:function(a,b){var d=this.entities,e={},c={},g,i,j,k,l,n,o,p;for(o=a.length;o--;)if(g=a[o],i=g.internalid,l=g.newid?g.newid:i,j=g.sname,g=g.lname,(k=d[i])&&!(l!==i&&d[l])){e[l]=l={origId:i};c[i]=!0;for(n in k)l[n]=k[n];l.shortLabel=j?j:k.shortLabel;
l.label=g?g:k.label}this.entities={};for(p in e)e[p].origId=p,this.entities[p.toLowerCase()]=e[p];for(p in d)if(!c[p])for(n in l=d[p],b.useSNameAsId?(this.entities[l.shortLabel.toLowerCase()]=k={},k.origId=l.shortLabel):(this.entities[p.toLowerCase()]=k={},k.origId=p),l)k[n]=l[n]},colorPaletteMap:{basefontcolor:"foregroundcolor",bordercolor:"foregrounddarkcolor",borderalpha:"foregrounddarkalpha",bgcolor:"backgroundlightcolor",bgalpha:"backgroundlightalpha",bgangle:"backgroundlightangle",bgratio:"backgroundlightratio",
canvasbordercolor:"foregrounddarkcolor",canvasborderalpha:"foregrounddarkalpha",canvasbgcolor:"backgroundlightcolor",canvasbgalpha:"backgroundlightalpha",canvasbgangle:"backgroundlightangle",canvasbgratio:"backgroundlightratio",tooltipbordercolor:"foregrounddarkcolor",tooltipborderalpha:"foregrounddarkalpha",tooltipbgcolor:"backgroundlightcolor",tooltipbgalpha:"backgroundlightalpha",tooltipfontcolor:"foregroundcolor",legendbordercolor:"foregrounddarkcolor",legendborderalpha:"foregrounddarkalpha",
markerbordercolor:"foregroundlightcolor",markerborderalpha:"foregroundlightalpha",markerbgcolor:"backgrounddarkcolor",markerbgalpha:"backgrounddarkalpha",markerbgangle:"backgrounddarkangle",markerbgratio:"backgrounddarkratio",plotfillcolor:"backgroundcolor",plotfillalpha:"backgroundalpha",plotfillangle:"backgroundangle",plotfillratio:"backgroundratio",plothoverfillcolor:"backgrounddarkcolor",plothoverfillalpha:"backgrounddarkalpha",plothoverfillangle:"backgrounddarkangle",plothoverfillratio:"backgrounddarkratio",
plotbordercolor:"foregroundcolor",plotborderalpha:"foregroundalpha",shadow:"shadow"},eiMethods:{getMapName:function(){return this.jsVars.instanceAPI.name},getEntityList:function(){var a=this.jsVars.instanceAPI,a=a.hcInstance&&a.hcInstance.entities&&a.hcInstance.entities.items,b=[void 0],d,e,c;for(d in a)e=a[d],c=e.options,b.push({id:e.id,originalId:e.originalId||e.id,active:e.isVisible,lName:c.label,sName:c.shortLabel,value:e.value,formattedValue:e.formattedValue,toolText:e.toolText});return b},getDataAsCSV:function(){var a=
this.jsVars.instanceAPI,a=a.hcInstance&&a.hcInstance.entities&&a.hcInstance.entities.items,b='"Id","Short Name","Long Name","Value","Formatted Value"',d,e,c,g;for(d in a)e=a[d],c=e.options,g=e.value,b+='\r\n"'+e.id+'","'+c.shortLabel+'","'+c.label+'","'+(g===void 0?"":g)+'","'+e.formattedValue+'"';return b},getMapAttribute:function(){var a=this.jsVars.fcObj;aa.raiseWarning(this,"12061210581","run","JavaScriptRenderer~getMapAttribute()",'Use of deprecated "getMapAttribute()". Replace with "getChartAttribute()".');
return a.getChartAttribute.apply(a,arguments)},exportMap:function(){var a=this.jsVars.fcObj;aa.raiseWarning(this,"12061210581","run","JavaScriptRenderer~exportMap()",'Use of deprecated "exportMap()". Replace with "exportChart()".');return a.exportChart&&a.exportChart.apply(a,arguments)}}},$.linebase);za.geo=Z.extendClass(za.line,{type:"geo",simpleSymbol:!0,render:function(){var a=this.chart,b=this.options.animation&&this.animate;if(!a.entities)this.mapGroup=this.group=a.renderer.g("series").add(a.seriesGroup),
b&&this.animate(!0),this.processEntityDefs(),this.alignMap(),this.drawEntities(),this.drawTrackers(),this.drawMarkers(),b&&this.animate()},animate:function(a){if(M){var b=jQuery(this.group.element);a?b.attr({opacity:0}):b.animate({opacity:1},this.options.animation)}},processEntityDefs:function(){var a=this.chart.options,b=a.instanceAPI;b.redefineEntities(b.dataObj.entitydef||[],a.entitydef)},alignMap:function(){var a=this.chart.options,b=a.instanceAPI,a=a[na],d=b._scaleFactor;this.group.align({align:"center",
verticalAlign:"middle",width:b.baseWidth*d,height:b.baseHeight*d},!0,{x:a.trackerLeft,y:a.trackerTop,width:a.viewportWidth,height:a.viewportHeight})},setScaleRange:function(a,b){var f;var d=this.options,e=this.chart,c=e.options[na],g=c.useValuesForMarkers?e.markers:e.entities,e=g.items||g.markerElemObj,c=c.useValuesForMarkers?{show:function(a){g.setMarkerVisibility(!0,a)},hide:function(a){g.setMarkerVisibility(!1,a)}}:{show:function(a){a.show()},hide:function(a){a.hide()}},i=d.data,j=i&&i.length,
k;if(d.rangeMin>=a&&d.rangeMax<=b){if(!d.allVisible)this.setVisible(!0),d.allVisible=!0}else if(d.rangeMax<a||d.rangeMin>b){if(!d.allHidden)this.setVisible(!1),d.allHidden=!0}else{d.allVisible=!1;for(d.allHidden=!1;j--;)d=i[j].id.toLowerCase(),f=(k=e[d])&&k.value,d=f,isNaN(d)||(d&&d>=a&&d<=b?c.show(k):c.hide(k))}},setVisible:function(a){var b=this.chart,d=b.options[na],e=this.legendItem,c=this.visible,g=this.data,i=d.useValuesForMarkers?b.markers:b.entities,j=i.items||i.markerElemObj,d=d.useValuesForMarkers?
{"true":function(a){i.setMarkerVisibility(!0,a)},"false":function(a){i.setMarkerVisibility(!1,a)}}:{"true":function(a){a.show()},"false":function(a){a.hide()}};this.visible=a=a===void 0?!c:a;e&&b.legend.colorizeItem(this,a);for(b=g&&g.length;b--;)e=g[b].id.toLowerCase(),(e=j[e])&&d[a.toString()](e)},drawEntities:function(){var a=this.chart,b=a.options&&a.options.instanceAPI;a.entities=new l(b&&b.dataObj&&b.dataObj.data,a,this.mapGroup)},drawTrackers:function(){this.chart.entities.drawTrackers()},
drawMarkers:function(){var a=this.chart,b=(a&&a.options&&a.options.instanceAPI).dataObj;if(b&&b.markers)a.markers=new Ka(b.markers,a)},getAttribs:function(){},getSymbol:function(){},destroy:function(){var a=this.chart;a.entities&&(a.entities.destroy(),delete a.entities);a.markers&&(a.markers.destroy(),delete a.markers)}})},[3,2,0,"release"]]);
